### ISSUE TITLE
Support crop on Android

### ISSUE THREAD

**Issue by Michaelvilleneuve** [Michaelvilleneuve/react-native-perspective-image-cropper#1]
UI is working just fine on Android but crop method has yet to be ported to android. OpenCV being available on android too, that should not be too long

**Comment by blaues0cke** [comment]
@Michaelvilleneuve Just to be sure: Do you have already any progress or (un)table Android code on this as you said in #3? Thinking about implementing this otherwise.

**Comment by Michaelvilleneuve** [comment]
Hi, I have not been able to work on it. Would be awesome if you could manage to get it to work :)
