### ISSUE TITLE
Could not build

### ISSUE THREAD

**Issue by tskorupka** [Michaelvilleneuve/react-native-perspective-image-cropper#10]
Hello,

I could not build RNCustomCrop.

What failed?

Failed: `#1 line: #import <opencv2/opencv.hpp>` for file CustomCropManager.mm. 
During build there was issue: Lexical or Preprocessor Issue. `'opencv2/opencv.hpp' file not found`.

Done everything like was written in README.md on repository.

**Comment by Michaelvilleneuve** [comment]
Hi ! OpenCV can sometimes be a pain in the ass to install...
Try this and tell me if it helps : https://www.youtube.com/watch?v=aZ8j_M_837Q&feature=youtu.be

**Comment by tskorupka** [comment]
I think I found how to resolve issue.

First by adding $(PROJECT_DIR)/../../../ios to Header Search Paths and Framework Search Paths.
Secondary by reading library in Link Binary with Libraries under Build Phases.
