### ISSUE TITLE
Cropping not correct and on head

### ISSUE THREAD

**Issue by danmoebius** [Michaelvilleneuve/react-native-perspective-image-cropper#18]
Hi,
i got to implement your package in my react native app. But i get trouble with the output image. If i use the full image size as rectangle coordinates, i will get only a part of the document, but not the full one. Second problem is, that the image will be on head. Have you any idea to solve these troubles? How decide opencv to get only part of the document? If there any properties to handle opencv? 

Origin Document:
![origin](https://user-images.githubusercontent.com/5362336/52132560-b308bc00-263f-11e9-9d12-d8ce7c23a0b0.png)
 
Cropped:
![cropped](https://user-images.githubusercontent.com/5362336/52132602-c87de600-263f-11e9-9944-3b8c049ebe67.png)

Best regards

**Comment by danmoebius** [comment]
Could be closed. I found the issue on my own, regarding to wrong rectangle coordinates.

**Comment by armin23615** [comment]
How did you solve this? 
Can you post your code, please?

**Comment by danmoebius** [comment]
Hi armin, 

i solved this problem by pre calculation of the rectangle coordinates. 

`getImageCroppingInformations = (imageWidth, imageHeight) => {
    let ratio = imageHeight / imageWidth;
    let calculatedWidth = width;
    let calculatedHeight = calculatedWidth * ratio;

    let positionLeft =
      calculatedWidth * DEFAULT_MARGIN_CROPPING_HANDLER_PERCENT;
    let positionRight =
      (calculatedWidth - doubleCroppingViewMargin) *
      (1 - DEFAULT_MARGIN_CROPPING_HANDLER_PERCENT);

    if (imageHeight > imageWidth) {
      ratio = imageWidth / imageHeight;
      calculatedWidth = height * ratio;
      calculatedHeight = determineHeight(
        DEFAULT_HEADER_HEIGHT + DEFAULT_BOTTOM_CONTROLS_HEIGHT
      );
    }

    let positionTop =
      calculatedHeight * DEFAULT_MARGIN_CROPPING_HANDLER_PERCENT;
    let positionBottom =
      (calculatedHeight - doubleCroppingViewMargin) *
      (1 - DEFAULT_MARGIN_CROPPING_HANDLER_PERCENT);

    return {
      positionLeft: positionLeft,
      positionRight: positionRight,
      positionTop: positionTop,
      positionBottom: positionBottom,
      calculatedWidth: calculatedWidth,
      calculatedHeight: calculatedHeight
    };
  };` 

But in fact, we kicked this repository out of our project, because it does not fulfill our expectations. In my humble opinion, in general check your requirements and think about to build by your own for more stability, customizability and update capability. 
Best regards

**Comment by rosenexpend** [comment]
@danmoebius I am working on getting the `react-native-perspective-image-cropper` to work on iOS. I created an [example](https://github.com/rosenexpend/rectangle-scanner-example) that works in a similar way to the component in my project. However, I am also experiencing an issue that the code on iOS does not seem to crop according to coordinates. It seems like you may have fixed this issue. Based on your code snippet above, I was wondering where `DEFAULT_MARGIN_CROPPING_HANDLER_PERCENT`, `doubleCroppingViewMargin`, `determineHeight(
    DEFAULT_HEADER_HEIGHT + DEFAULT_BOTTOM_CONTROLS_HEIGHT
  );`.

The code for my Cropper component is below:
```
'use strict';
import React, {Component} from 'react';
import {
  View,
  Text,
  Button,
  Image,
  TouchableHighlight,
  StyleSheet,
  Dimensions,
  SafeAreaView,
} from 'react-native';
import CustomCrop from 'react-native-perspective-image-cropper';
import ImagePicker from 'react-native-image-crop-picker';
import ImageViewer from './ImageViewer';
import {
  responsiveScreenHeight,
  responsiveScreenWidth,
} from 'react-native-responsive-dimensions';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

class ImageCropper extends Component {
  constructor(props) {
    super(props);
    const {route} = props;
    const windowWidth = Dimensions.get('screen').width;
    const windowHeight = Dimensions.get('screen').height;

    const DEFAULT_IMAGE_HEIGHT = 3264;
    const DEFAULT_IMAGE_WIDTH = 2448;

    this.state = {
      image: '',
      initialImage: this.props.imageParam,
      rectangleCoordinates: this.props.rectangleCoordinates,
      imageWidth: DEFAULT_IMAGE_WIDTH,
      imageHeight: DEFAULT_IMAGE_HEIGHT,
      imageViewed: false,
    };
  }

  componentDidMount() {
    console.log('imageParam', this.props.imageParam);
    console.log('rectangleCoordinates', this.props.rectangleCoordinates);
    Image.getSize(this.props.imageParam, (width, height) => {
      this.setState({
        imageWidth: width,
        imageHeight: height,
      });
    });
  }

  updateImage(image, newCoordinates) {
    this.setState({
      image,
      rectangleCoordinates: newCoordinates,
    });
    console.log(image);
    if (this.state.image.length > 0) {
      this.setState({
        imageViewed: true,
      });
    }
  }

  crop() {
    this.customCrop.crop();
  }

  render() {
    const {image, imageWidth, imageHeight} = this.state;
    return (
      <>
        {this.state.imageViewed ? (
          <ImageViewer
            croppedImage={image}
            imageWidth={imageWidth}
            imageHeight={imageHeight}
            onImageCropped={this.props.onImageCropped}
          />
        ) : (
          <SafeAreaView style={styles.safeArea}>
            <View style={[styles.container]}>
              <View style={{flex: 5}}>
                <View style={styles.imageCropper}>
                  <CustomCrop
                    updateImage={this.updateImage.bind(this)}
                    rectangleCoordinates={this.state.rectangleCoordinates}
                    initialImage={this.state.initialImage}
                    height={this.state.imageHeight}
                    width={this.state.imageWidth}
                    ref={(ref) => (this.customCrop = ref)}
                    overlayColor="rgba(18,190,210, 1)"
                    overlayStrokeColor="rgba(20,190,210, 1)"
                    handlerColor="rgba(20,150,160, 1)"
                    enablePanStrict={false}
                  />
                </View>
              </View>
              <View style={{flex: 1}}>
                <TouchableHighlight
                  style={styles.cropButtonTouchable}
                  onPress={this.crop.bind(this)}>
                  <View style={styles.cropButton}>
                    <Text style={styles.cropButtonLabel}>Crop Image</Text>
                  </View>
                </TouchableHighlight>
              </View>
            </View>
          </SafeAreaView>
        )}
      </>
    );
  }
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 6,
    alignSelf: 'flex-start',
    justifyContent: 'center',
  },
  imageCropper: {
    height: hp('100%'),
  },
  container: {
    flex: 1,
    flexDirection: 'column',
  },
  cropButtonTouchable: {
    flex: 2,
    alignSelf: 'center',
    marginTop: 12,
  },
  cropButton: {
    padding: 12,
    backgroundColor: 'blue',
    justifyContent: 'center',
    borderRadius: 4,
  },
  cropButtonLabel: {
    color: 'white',
    fontSize: 16,
    fontWeight: '500',
  },
  text: {
    color: 'white',
  },
});

export default ImageCropper;
```

**Comment by cdcharlebois** [comment]
@danmoebius was there an alternative library that you found to provide this perspective-cropping functionality? I'm currently stuck on a similar issue

**Comment by danmoebius** [comment]
@cdcharlebois i am sorry, I have no alternativ Library. I changed a lot of these library to make it useful for our case. But I think the best method will be a custom solution on your case with opencv. I know it is more work, but you are save in case of updates. 

If you find another library. Let us know 😊
Best regards

**Comment by cdcharlebois** [comment]
please see my PR #64
