### ISSUE TITLE
error: cannot find symbol import org.opencv.RNCustomCropPackage;

### ISSUE THREAD

**Issue by zahidahmed024** [Michaelvilleneuve/react-native-perspective-image-cropper#25]
"dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-perspective-image-cropper": "^0.4.3",
    "react-native-svg": "^9.5.1"
  },

**Comment by hoboxdomotica** [comment]
same here please help

**Comment by Michaelvilleneuve** [comment]
Hi, did you properly linked the additional open cv dependency as explained in the readme ?
Do you know which line exactly causes the error ?

**Comment by zahidahmed024** [comment]
i added "import fr.michaelvilleneuve.customcrop.RNCustomCropPackage; " and removed "import org.opencv.RNCustomCropPackage" in myapplication and the error is gone , 

 :'( . now im facing failded to get image size :'(   .
would u please attach a example project .it will be helpful for us :'( :'(

**Comment by Michaelvilleneuve** [comment]
I will try to provide an example project.
The error means that the native module has not been linked properly

**Comment by zahidahmed024** [comment]
hey i did it ,, i installed opencv  manually .. thank u so much  :D :D ,

**Comment by Michaelvilleneuve** [comment]
Well done ! What differs from the provided documentation ? Should we update it ?

**Comment by ZohaibAhmad786** [comment]
`import org.opencv.RNCustomCropPackage;
                 ^
  symbol:   class RNCustomCropPackage
  location: package org.opencv
D:\Copy Freelance Projects\PerspectiveCorpper\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:18: error: cannot find symbol
import org.opencv.RNCustomCropPackage;
                 ^
  symbol:   class RNCustomCropPackage
  location: package org.opencv`


still facing the same issue

**Comment by ZohaibAhmad786** [comment]
help me out this problem.

**Comment by ambessh** [comment]
put this in MainApplication.java
import  fr.michaelvilleneuve.customcrop.RNCustomCropPackage;

and make a new file in node modules react native perspective image cropper folder named  "react-native.config.js"
and paste the following code within it.

module.exports = {
  dependency: {  
    platforms: {  
      android: {  
        packageImportPath: 'import fr.michaelvilleneuve.customcrop.RNCustomCropPackage;',  
        packageInstance: 'new RNCustomCropPackage()',  
      },  
    },  
  },  
};
