### ISSUE TITLE
Getting native exception on crop - iOS

### ISSUE THREAD

**Issue by nimrod-zg** [Michaelvilleneuve/react-native-perspective-image-cropper#27]
We are getting this exception when calling `crop()` on some iPhone models. We haven't managed to pinpoint the issue exactly, but it seems to be occurring on newer models like the iPhone X, rather than on older ones like the 6. Looking online for this error and finding that the issue happens on newer, presumably faster, iPhones causes us to think it may be some timing issue with accessing the file or something, but we could be in the wrong direction. The issue does not recreate on an iPhone X simulator.

```
RCTFatalException: Exception '*** 
-[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert
 nil object from objects[0]' was thrown while invoking crop on target 
CustomCropManager with params (
        {
        bottomLeft =         {
            x = "302.3999999999999";
            y = "2419.2";
        };
        bottomRight =         {
            x = "2721.6";
            y = "2419.2";
        };
        height = 4032;
        topLeft =         {
            x = "302.3999999999999";
            y = "403.2";
        };
        topRight =         {
            x = "2721.6";
            y = "403.2";
        };
        width = 3024;
    },
    "file:///PATH/initial_img_1560416408.jpeg",
    65949
)
```

Any advice on how to solve this, or even debug this, is welcome.

**Comment by Michaelvilleneuve** [comment]
Hi ! 
Your params seem ok. Are you sure that the image given at this filepath exists ? 
You could try to debug it step by step in xcode, that would allow you to understand when a nil object is given.

**Comment by nimrod-zg** [comment]
A few updates, and some more info that I should have included before - 
1. We managed to recreate this on all testes iOS devices (iPhone 6, 7, X, iPad)
2. We've tried debugging this using xCode - this issue will not recreate while debugging, even if we build with Release settings, so no luck with that.
3. Something I failed to mention last time - the input image we pass to the cropper is generated by manually capturing an image with your other library, `react-native-document-scanner`.

Our current flow -
1. Manually capture an image using `react-native-document-scanner`.
2. Receive the file path of the newly created picture in the `onPictureTaken` callback, this is similar to`/private/var/mobile/Containers/Data/Application/0C941FC0-7A82-4F99-8209-65D7ACD1E0FF/tmp/initial_img_1560416408.jpeg`
3. Prefixing the path with `file://` and passing this to the `CustomCrop` in the `initialImage` prop.
4. Call `crop()`. When not in debug, this causes the error detailed above.

Things to note and open questions -
- The image is previewed correctly before the we call `crop()`, so it seems like the file exists and can be read.
- Trying to copy the image into a separate file before passing it to the CustomCrop element did not make any difference, still getting the same error.
- In the `README.md` the `initiailImage` prop described as "Base64 encoded image you want to be cropped". From playing around and reading the native code, this seem to be outdated, as it seems like passing just the base64 data, or even a data URL, is no supported.
- From the debugging we did the hunch we have is that the root of the error is [in this line](https://github.com/Michaelvilleneuve/react-native-perspective-image-cropper/blob/master/ios/CustomCropManager.mm#L12),  when a failure to read the file into a `CIImage` object is causing the `ciImage` variable to be set to `nil`. What we're failing to understand is why is the file failing to be read. Is it possible that there is some hidden permissions issue or something like that? This sounds unlikely because the file is being read correctly be the preview `Image` RN component, but it's the only idea we have at the moment.

**Comment by Michaelvilleneuve** [comment]
Hi @nimrod-zg sorry I don’t have time to help. Have you found a way to fix your problem ?

**Comment by nimrod-zg** [comment]
@Michaelvilleneuve - closed this issue now as this seems to have been some strange build issue or something. We've just finished releasing a new native version for iOS without making any changes to the code and this seems to have - somewhat frustratingly I must say - completely resolved the issue 🤦‍♂ 
Anyway, we're good now 🤷‍♂ 
Thank you!
