### ISSUE TITLE
" React Native perspective image cropper " android compatible ?

### ISSUE THREAD

**Issue by SainiRohitSeasia** [Michaelvilleneuve/react-native-perspective-image-cropper#3]
Is this library compatible with both android and ios  by using image's base64 path ?

**Comment by Michaelvilleneuve** [comment]
The JS and UI part is fully android compatible but I'm still working on making the actual crop method work.

This should not be too long but it has yet to be implemanted

**Comment by Michaelvilleneuve** [comment]
I close this issue in favor of #1
