### ISSUE TITLE
How to change Image Size in Cropper?

### ISSUE THREAD

**Issue by abstruse9** [Michaelvilleneuve/react-native-perspective-image-cropper#30]
![photo_2019-10-26_17-35-13](https://user-images.githubusercontent.com/20104752/67619272-17dff400-f817-11e9-8d8c-84e8df90ba7f.jpg)

Code 

```
                     <CustomCrop
                        updateImage={updateImage}
                        rectangleCoordinates={coords}
                        initialImage={image}
                        height={height}
                        width={width}
                        ref={(ref) => {
                            customCrop = ref;
                        }}
                        overlayColor="rgba(18,190,210, 1)"
                        overlayStrokeColor="rgba(20,190,210, 1)"
                        handlerColor="rgba(20,150,160, 1)"
                        enablePanStrict={false}
                    />
```

I'd need the Image Cropper Area (Red Border Box) to expand a bit down, so the image is seen big enough to adjust crop points

**Comment by SL-A-SH** [comment]
I am using RNCamera module so I forced the orientation to portrait mode. It is coming in full screen with portrait mode.

**Comment by SL-A-SH** [comment]
Were you able to fix this? I am facing the same issue now if I use an image picker library.

**Comment by abstruse9** [comment]
@SL-A-SH Yes, a workaround is, first make sure your photo is in portrait mode from your camera, then pass the value of of the longest side of photo to the `height` , in this way the photo is always fullscreen.

If you keep the `width` as longest then it will display as in the above issue.

so just supply the prop of `height` as 

```
import ImageCropModule from "react-native-perspective-image-cropper";

<ImageCropModule
  ...
  height={Math.max(height, width)}
  width={Math.min(height, width)}
  ref={ref => {
    customCrop = ref;
  }}
  ...
/>;
```

**Comment by SL-A-SH** [comment]
@abstruse9 Thanks. It did help. You can close the issue.

**Comment by SL-A-SH** [comment]
The issue is fixed but cropping is not working correctly now. It is only crops half the image.

**Comment by MITDD6338** [comment]
when clicking the image then **cropper is not open**  
anyone can help us? 
@abstruse9  @SL-A-SH

**Comment by SL-A-SH** [comment]
@MITDD6338 Post your error or a screenshot

**Comment by abstruse9** [comment]
@SL-A-SH Strange. Try logging the coordinates of the image in the cropper module's index.js file in the `crop()` method, and cross verify if the Cropper's coordinates match your area selection

**Comment by SL-A-SH** [comment]
@abstruse9 No it does not match. The top left and top right coordinates are starting from half of the image. 
Also note that my image was captured in landscape mode not portrait mode since I cannot ensure the image taken was in landscape or portrait.
So when the image was taken in landscape mode the image inside cropper is centered in the screen with black spaces above and below it and not just in the top like in the screenshot you posted.

**Comment by MITDD6338** [comment]
@SL-A-SH

 **see image and video** 

![Image from iOS](https://user-images.githubusercontent.com/31823903/68382258-5b245600-0179-11ea-93f8-2da30d144635.png)

**Comment by abstruse9** [comment]
@SL-A-SH 

Can you post an example screenshot of your photo? and how it is aligned?

**Comment by MITDD6338** [comment]
https://drive.google.com/file/d/1FVrTt0N5cKh9EsqGnI4Y7mH_iLlEPCMA/view?usp=sharing
@SL-A-SH

**Comment by MITDD6338** [comment]
@abstruse9 
your crop can be open?

**Comment by SL-A-SH** [comment]
@abstruse9 

This is how it appears inside cropper. The image was taken in landscape mode and is coming in the center of the screen due to your solution.

![Screenshot_20191107-162619](https://user-images.githubusercontent.com/22798524/68383406-9aec3d00-017b-11ea-984a-901d34af2451.png)

This is how it appears after cropping. Notice only half of the card is cropped even though the whole card is selected. 

![cbimage](https://user-images.githubusercontent.com/22798524/68383475-bd7e5600-017b-11ea-8c2c-b81b192a4eca.jpg)

**Comment by SL-A-SH** [comment]
@MITDD6338 Have you linked this package correctly for IOS. If yes can you also post your Cropper Component where you implemented this package.

**Comment by MITDD6338** [comment]
import React, {Component} from 'react';
import {
  Dimensions,
  StyleSheet,
  Text,
  Image,
  TouchableOpacity,
  View,
} from 'react-native';
import Scanner from 'react-native-document-scanner';
import CustomCrop from 'react-native-perspective-image-cropper';

export default class Scanners extends Component {
  constructor(props) {
    super(props);
    this.state = {
      image: null,
      flashEnabled: false,
      useFrontCam: false,
      rectangleCoordinates: null,
      initialImage: null,
      stableCounter: '',
      lastDetectionType: '',
      height: 200,
      width: 200,
    };
    this.updateImage = this.updateImage.bind(this);
    this.crop = this.crop.bind(this);
  }

  updateImage(image, newCoordinates) {
    this.setState({
      image,
      rectangleCoordinates: newCoordinates,
    });
  }

  crop() {
    this.customCrop.crop();
  }

  componentWillMount() {
    const {image, initialImage} = this.state;
    initialImage == null
      ? null
      : Image.getSize(initialImage, (width, height) => {
          console.warn(width, height);
          this.setState({
            imageWidth: width,
            imageHeight: height,
            initialImage: initialImage,
            rectangleCoordinates: {
              topLeft: {x: 10, y: 10},
              topRight: {x: 10, y: 10},
              bottomRight: {x: 10, y: 10},
              bottomLeft: {x: 10, y: 10},
            },
          });
        });
  }

  renderDetectionType() {
    switch (this.state.lastDetectionType) {
      case 0:
        return 'Correct rectangle found';
      case 1:
        return 'Bad angle found';
      case 2:
        return 'Rectangle too far';
      default:
        return 'No rectangle detected yet';
    }
  }

  render() {
    const {height, width} = this.state;
    return (
      <View style={styles.container}>
        {this.state.initialImage ? (
          <View>
            <CustomCrop
              updateImage={this.updateImage}
              rectangleCoordinates={this.state.rectangleCoordinates}
              initialImage={this.state.initialImage}
              height={height}
              width={width}
              ref={ref => (this.customCrop = ref)}
              overlayColor="rgba(18,190,210, 1)"
              overlayStrokeColor="rgba(20,190,210, 1)"
              handlerColor="rgba(20,150,160, 1)"
              enablePanStrict={false}
            />
            <TouchableOpacity onPress={this.crop.bind(this)}>
              <Text>CROP IMAGE</Text>
            </TouchableOpacity>
          </View>
        ) : (
          <Scanner
            onPictureTaken={data => {
              this.setState({
                image: data.croppedImage,
                rectangleCoordinates: data.rectangleCoordinates,
                initialImage: data.initialImage,
              });
            }}
            overlayColor="rgba(255,130,0, 0.7)"
            enableTorch={this.state.flashEnabled}
            useFrontCam={this.state.useFrontCam}
            brightness={0.2}
            saturation={0.01}
            quality={0.5}
            contrast={1.2}
            onRectangleDetect={({stableCounter, lastDetectionType}) => {
              this.setState({stableCounter, lastDetectionType});
            }}
            detectionCountBeforeCapture={5}
            detectionRefreshRateInMS={50}
            style={styles.scanner}
          />
        )}

        <Text style={styles.instructions}>
          {this.state.stableCounter || 0} correctly formated rectangle detected
        </Text>
        <Text style={styles.instructions}>{this.renderDetectionType()}</Text>
        {this.state.image === null ? null : (
          <TouchableOpacity
            style={styles.newPic}
            onPress={() => this.setState({image: ''})}
          >
            <Text>Take another picture</Text>
          </TouchableOpacity>
        )}
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
  },
  newPic: {
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    backgroundColor: 'yellow',
  },
  button: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    top: 20,
    bottom: 20,
    height: 40,
    width: 120,
    backgroundColor: '#FFF',
  },
  left: {
    left: 20,
  },
  right: {
    right: 20,
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: 'black',
    marginBottom: 5,
  },
  scanner: {
    flex: 1,
    width: 400,
    height: 200,
    borderColor: 'orange',
    borderWidth: 1,
  },
});

**Comment by abstruse9** [comment]
@SL-A-SH 

So the way this package was probably implemented, if you take photos in landscape mode, and supply the height as long side of image, then the cropper area will be swapped, hence why you're getting wrong crop. Because Image Height does not match with Cropper Height Setting. 

My solution would only work if you force all images to display as full size portrait.

If it's shot like landscape (centered with black spaces above and below) then you need to pass original image dimension values. 

I too am not sure about this, I didn't test it. But this package has poor aspect ratio support.

**Comment by MITDD6338** [comment]
@SL-A-SH 

yes I was linked
<img width="189" alt="Screenshot 2019-11-07 at 4 41 14 PM" src="https://user-images.githubusercontent.com/31823903/68384354-74c79c80-017d-11ea-9679-3f8ba26f608f.png">



<img width="220" alt="Screenshot 2019-11-07 at 4 40 54 PM" src="https://user-images.githubusercontent.com/31823903/68384355-74c79c80-017d-11ea-88c8-fbc0dc5c1a7d.png">

**Comment by MITDD6338** [comment]
@abstruse9  
How can your Crop border like blue is visible? can u share with 
because my crop was not open

**Comment by SL-A-SH** [comment]
@abstruse9 

> But this package has poor aspect ratio support.
I agree with you.

> If it's shot like landscape (centered with black spaces above and below) then you need to pass original image dimension values.
If I pass the original image dimension values then the image will not be centered in the screen. It will show in the top of the screen like in your screenshot and that's just bad UX.

**Comment by MITDD6338** [comment]
@SL-A-SH 
can u help with I share my implementation code

**Comment by SL-A-SH** [comment]
@MITDD6338 Can you just try picking an image from an image-picker and implement it with the cropper and see if it works? Also can you open a new issue as this one is closed and other people might be able to help you too.

**Comment by MITDD6338** [comment]
@SL-A-SH okay
