### ISSUE TITLE
getting undefinded object corner.x error on custom cropper load

### ISSUE THREAD

**Issue by kavsar14** [Michaelvilleneuve/react-native-perspective-image-cropper#56]
![Screenshot 2021-03-06 at 5 50 36 PM](https://user-images.githubusercontent.com/49279708/110206650-009e2580-7ea5-11eb-8bdb-1ecc5e1f31ed.png)

Hello, i am getting undefined object corner.x error on cropper load..i have set all the example code mentioned things in my code..initial image etc..

**Comment by kavsar14** [comment]
i forgot to make Image.getSize function await

**Comment by saniaayoub** [comment]
Please explain a bit more i am having same issue

> i forgot to make Image.getSize function await
