### ISSUE TITLE
Option to use file URI's instead of base64 for input/output

### ISSUE THREAD

**Issue by nabati** [Michaelvilleneuve/react-native-perspective-image-cropper#6]
For performance and compatibility. Let me know if you think it's a good idea.

**Comment by Michaelvilleneuve** [comment]
Same as the scanner, would be a great option ! Actually in production the communication between both for one image lasts around 200ms, I'm sure we could greatly improve that by passing file's uri

**Comment by poyannabati** [comment]
I'll look into it soon!

**Comment by Michaelvilleneuve** [comment]
If your projects lead you to work regularly on scanners I would be happy to add you as a collaborator. Especially since I don't work on it for now !

**Comment by Michaelvilleneuve** [comment]
Fixed by 1832cb84a2ccd6369f098655788fd5d4093b6be4 input must now be a file path

**Comment by antoinerousseau** [comment]
The doc should be updated then
